### ISSUE TITLE
Some problem of 52Poke

### ISSUE THREAD

**Issue by Asriel-cyrus** [mudkipme/klinklang#4]
I am PikAsriel from 52Poké. Can you add the function Imagemap from mediawiki so that we can have better quality to show the picture, instead of using template? In additional, I want to ask that how we can have robot account because I saw a user who has recently a new robot but without discussion. Thank you.

**Comment by mudkipme** [comment]
Moved to https://github.com/mudkipme/52poke/issues/19.

This repository is about the utilities of 52Poké Wiki on https://util.52poke.wiki or programmable automations. Please use [mudkipme/mediawiki](https://github.com/mudkipme/mediawiki) to propose installing new extension and [mudkipme/52poke](https://github.com/mudkipme/52poke) to request enabling built-in extensions or configuring existing extensions.

See [mudkipme/52poke](https://github.com/mudkipme/52poke) and [its wiki](https://github.com/mudkipme/52poke/wiki) about open source projects related to 52Poké.

For your other question, I've replied your previous email. Thanks for using GitHub to open technical issues of 52Poké.
